#!/bin/bash 

rm posts_temp

for f in ../markdown/*.md;
do	
    [ -e "$f" ] || continue
    FILE="$f"
    DATE=$(echo $FILE | cut -d"/" -f 3 | cut -d"_" -f 1)
    TITLE=$(echo $FILE | cut -d"_" -f 2 | cut -d "." -f 1)
    
    echo $TITLE

    pandoc "$FILE" \
	--template post.template.html \
	--metadata title="$TITLE" \
	--metadata date="$DATE" \
	--katex \
	--highlight-style pygments \
	-o "../posts/$DATE.html"
    OUT="""
    <div class='container preview'>
	<a href='/posts/$DATE.html'>
	  <img src='/statics/post_bg/$DATE.jpg' class='preview-image'>
	  <p class='preview-caption'> $TITLE </p>
	</a>
    </div>
    """
    echo $OUT >> posts_temp
done

tac posts_temp > posts_temp2

FILE1=$(<post.list.template.html)
FILE2=$(<posts_temp2)
echo "${FILE1//CONTENT/$FILE2}" > ../posts.html

rm posts_temp posts_temp2

