#!/bin/bash

WEBSITE_DIR=$HOME/Projects/Archive/Personal_Website/mkomodromos_template
DEPLOY_DIR=$HOME/Projects/Archive/Personal_Website/mkomod.github.io

### UNCOMMENT FOR RSYNC DEPLOY
# rsync -a \
#     --quiet \
#     -e ssh $WEBSITE_DIR <SERVER IP>:/path/to/deploy/dir

### UNCOMMENT FOR GITHUB IO DEPLOY

cd $DEPLOY_DIR
rm -r *
cp -r $WEBSITE_DIR/* ./
git add .
git commit -m "auto update"
git push

